<?php

use common\models\Order;
use common\utils\ImageUtil;
use common\widgets\ConfirmDialog;
use common\widgets\ImageDialog;
use common\widgets\StarsRating;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use common\widgets\FileAttachment;

$this->title = $order->name;

$this->registerJs(
	'$(window).bind("hashchange",  function(){'
		.'if (location.hash == null || location.hash == "" || location.hash == "#history"){'
			.'$.ajax({'
	  			.'method: "GET",'
	  			.'url: "'.Url::toRoute(['order/index']).'",'
	  			.'data: {"id": '.$order->id.'}'
			.'})'
	  			.'.done(function(order) {'
					.'if (order != ""){'
						.'drawHitory(order);'
					.'}'
	  			.'});'
		.'} else if (location.hash == "#edit"){'
			.'$.ajax({'
	  			.'method: "GET",'
	  			.'url: "'.Url::toRoute(['order/index']).'",'
	  			.'data: {"id": '.$order->id.'}'
			.'})'
	  			.'.done(function(order) {'
					.'if (order != ""){'
						.'drawEditCard(order);'
					.'}'
	  			.'});'
		.'} else if (location.hash == "#messages"){'
			.''
		.'} else if (location.hash == "#proposals"){'
			.''
		.'}'
	.'});'
	.'var links = $("nav.sidebar-nav").find("li");'
	.'links.each(function() {'
		.'$(this).children().click(function(){'
			.'links.each(function() {'
				.'$(this).removeClass("is-active");'
			.'});'
			.'$(this).parent().addClass("is-active");'
		.'});'
	.'});'
	.'var drawHitory = function(order){'
		.'var content = $("#tab-content");'
		.'content.empty();'
		.'content.append(drawCloseCard(order)+drawMainCard(order));'
		.'loadImages(order);'
		.'initImageDialog();'
		.'initConfirmDialog();'
		.'var images = content.find(".images-content a");'
		.'content.find("#action_order").click(function(){'
			.'if (order["status"]=='.Order::STATUS_ACTIVE.'){'
				.'showConfirmDialog(function(){'
					.'setOrderStatus(order["id"], '.Order::STATUS_CLOSED.');'
				.'})'
			.'} else {'
				.'setOrderStatus(order["id"], '.Order::STATUS_ACTIVE.');'
			.'}'
		.'});'
	.'};'
	.'var drawCloseCard = function (order){'
		.'if (order["status"]!='.Order::STATUS_CLOSED.') return "";'
		.'return "<div class=\"close-card mdl-card mdl-shadow--2dp\">'
					.'<div class=\"mdl-card__title\">'
    					.'<h2 class=\"mdl-card__title-text\">Заказ закрыт</h2>'
						.'<time class=\"mdl-color-text--grey-600\">"+order["closeDate"]+"</time>'
  					.'</div>'
					.'<div class=\"mdl-card__supporting-text\">'
			    		.'Если вы хотите открыть заказ, сделайте это ниже.'
					.'</div>'
				.'</div>";'
	.'};'
	.'var drawMainCard = function (order){'
		.'var range = "";'
		.'if (order["rangeMin"] != null) {'
			.'range = "от "+order["rangeMin"];'
		.'}'
		.'if (order["rangeMax"] != null) {'
			.'if (range != null) {'
				.'range += " ";'
			.'}'
			.'range += "до "+order["rangeMax"];'
		.'}'
		.'return "<div class=\"history-card mdl-card mdl-shadow--2dp\">'
  				.'<div class=\"mdl-card__title\">'
    				.'<h2 class=\"mdl-card__title-text\">Заказ создан</h2>'
					.'<time class=\"mdl-color-text--grey-600\">"+order["createDate"]+"</time>'
  				.'</div>'
				.'<div class=\"mdl-card__supporting-text\">'
				    .'Поздравляем! Ваш заказ активирован.'
				.'</div>'
				.'<div class=\"mdl-card__actions mdl-card--border\">'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Название</div>'
						.'<div class=\"mdl-cell mdl-cell--9-col\"><h2 class=\"mdl-card__title-text\">"+order["name"]+"</h2></div>'
					.'</div>'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Мастер</div>'
						.'<div class=\"master-content mdl-cell mdl-cell--9-col\">'
							.'<a class=\"avatar\" style=\"background-image: url(\''.ImageUtil::getAvatar('/user/'.$master->id).'\');\"></a>'
							.'<div class=\"details\">'
								.$master->lastName.' '.$master->firstName.'<br>'
								.$master->shop.' / '.$master->getPlace()->name.'<br>'
								.str_replace('"', '\"', StarsRating::widget([
										'rating' => 4,
										'reviews' => 10,
										'isSmall' => true,
								]))
							.'</div>'
						.'</div>'
					.'</div>'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Размер</div>'
						.'<div class=\"mdl-cell mdl-cell--9-col\">"+(order["size"]==null?"Размер не указан":order["size"])+"</div>'
					.'</div>'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Материалы</div>'
						.'<div class=\"mdl-cell mdl-cell--9-col\">"+(order["materials"]==null?"Материалы не указаны":order["materials"])+"</div>'
					.'</div>'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Бюджет</div>'
						.'<div class=\"mdl-cell mdl-cell--9-col\">"+(range==""?"Бюджет не задан":range+" руб.")+"</div>'
					.'</div>'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Описание</div>'
						.'<div class=\"mdl-cell mdl-cell--9-col\">"+order["details"]+"</div>'
					.'</div>'
					.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
						.'<div class=\"mdl-cell mdl-cell--3-col\">Изображения</div>'
						.'<div class=\"mdl-cell mdl-cell--9-col\">'
							.'<div class=\"images-content\"></div>'
						.'</div>'
					.'</div>'
				.'</div>'
				.'<div class=\"mdl-card__actions mdl-card--border\">'
					.'<a id=\"action_order\" class=\"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">"'
						.'+(order["status"]=='.Order::STATUS_ACTIVE.'?"Закрыть":"Возобновить")+"'
				    .'</a>'
					.'<a id=\"edit_order\" class=\"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\" href=\"'.Url::toRoute(['', 'id' => $order->id, '#' => 'edit']).'\">'
						.'Изменить'
				    .'</a>'
				.'</div>'
			.'</div>'
			.str_replace('"', '\"', ImageDialog::widget(['skipInit' => true]))
			.str_replace('"', '\"', ConfirmDialog::widget(['skipInit' => true]))
			.'";'
	.'};'
	.'var loadImages = function(order){'
		.'$.ajax({'
  			.'method: "GET",'
  			.'url: "'.Url::toRoute(['file/uploads']).'",'
  			.'data: {projectId: order["projectId"], orderId: order["id"]}'
		.'})'
  			.'.done(function(images) {'
				.'var imagesContent = $(".images-content");'
				.'images.paths.forEach(function(image) {'
					.'$(document.createElement("a"))'
    					.'.attr({style: "background-image: url(\'"+image+"\');", "data-original": image})'
    					.'.appendTo(imagesContent)'
					    .'.click(function(){'
							.'showImageDialog($(this).attr("data-original"));'
					    .'});'
				.'});'
  			.'});'
	.'};'
	.'var setOrderStatus = function(id, status){'
		.'$.ajax({'
  			.'method: "GET",'
  			.'url: "'.Url::toRoute(['order/status']).'",'
  			.'data: {"id": id, "status": status}'
		.'})'
  			.'.done(function(order) {'
				.'if (order != ""){'
					.'drawHitory(order);'
				.'}'
  			.'});'
	.'};'
	.'var drawEditCard = function(order){'
		.'var content = $("#tab-content");'
		.'content.empty();'
		.'content.append("<div class=\"close-card mdl-card mdl-shadow--2dp\">'
							.'<div class=\"mdl-card__title\">'
		    					.'<h2 class=\"mdl-card__title-text\">Редактирование заказа</h2>'
		  					.'</div>'
							.'<div class=\"mdl-card__supporting-text\">'
					    		.'Вы можите отредактировать ваш заказ здесь, изменения будут отправлены Мастеру.'
							.'</div>'
							.'<form id=\"OrderForm\" action=\"comment.php\" method=\"post\" class=\"mdl-card__actions mdl-card--border\">'
								.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
									.'<div class=\"mdl-cell mdl-cell--3-col mdl-textfield__title\">Название</div>'
									.'<div class=\"mdl-cell mdl-cell--9-col mdl-textfield mdl-js-textfield\">'
										.'<input class=\"mdl-textfield__input\" type=\"text\" maxlength=\"255\" name=\"title\" id=\"EditFormTitle\" value=\""+order["name"]+"\">'
										.'<label class=\"mdl-textfield__label\" for=\"EditFormTitle\">Краткое названия вашего проекта</label>'
									.'</div>'
								.'</div>'
								.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
									.'<div class=\"mdl-cell mdl-cell--3-col mdl-textfield__title\">Укажите размер</div>'
									.'<div class=\"mdl-cell mdl-cell--8-col mdl-textfield mdl-js-textfield\">'
										.'<input class=\"mdl-textfield__input\" type=\"text\" maxlength=\"250\" name=\"size\" id=\"EditFormSize\" value=\""+(order["size"]==null?"":order["size"])+"\">'
									    .'<label class=\"mdl-textfield__label\" for=\"EditFormSize\">Размер, единица измерения</label>'
									.'</div>'
								.'</div>'
								.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
									.'<div class=\"mdl-cell mdl-cell--3-col mdl-textfield__title\">Опишите материалы</div>'
									.'<div class=\"mdl-cell mdl-cell--8-col mdl-textfield mdl-js-textfield\">'
										.'<input class=\"mdl-textfield__input\" type=\"text\" maxlength=\"250\" name=\"materials\" id=\"EditFormMaterials\" value=\""+(order["materials"]==null?"":order["materials"])+"\">'
									    .'<label class=\"mdl-textfield__label\" for=\"EditFormMaterials\">Дерево, платина, изумруды и т.д.</label>'
									.'</div>'
								.'</div>'
								.'<div class=\"range mdl-grid mdl-card__subtitle-text\">'
									.'<div class=\"mdl-cell mdl-cell--3-col mdl-textfield__title\">Укажите диапазон бюджета</div>'
									.'<div class=\"mdl-cell mdl-cell--8-col mdl-grid\">'
										.'<span class=\" mdl-textfield__title\">от </span>'
										.'<div class=\"mdl-cell mdl-textfield mdl-js-textfield\">'
									    	.'<input class=\"mdl-textfield__input\" type=\"text\" pattern=\"-?[0-9]*(\.[0-9]+)?\" id=\"rangeMin\" value=\""+(order["rangeMin"]==null?"":order["rangeMin"])+"\">'
									    	.'<span class=\"mdl-textfield__error\">Значение не является числом</span>'
									  	.'</div>'
										.'<span class=\" mdl-textfield__title\"> до </span>'
										.'<div class=\"mdl-cell mdl-textfield mdl-js-textfield\">'
									    	.'<input class=\"mdl-textfield__input\" type=\"text\" pattern=\"-?[0-9]*(\.[0-9]+)?\" id=\"rangeMax\" value=\""+(order["rangeMax"]==null?"":order["rangeMax"])+"\">'
									    	.'<span class=\"mdl-textfield__error\">Значение не является числом</span>'
									  	.'</div>'
										.'<span class=\" mdl-textfield__title\"> рублей<span>'
									.'</div>'
								.'</div>'
								.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
									.'<div class=\"mdl-cell mdl-cell--3-col mdl-textfield__title\">Описание</div>'
									.'<div class=\"mdl-cell mdl-cell--8-col mdl-textfield mdl-js-textfield\">'
										.'<textarea rows=\"5\" class=\"mdl-textfield__input\" type=\"text\" maxlength=\"250\" name=\"details\" id=\"EditFormDetails\" value=\""+(order["details"]==null?"":order["details"])+"\"></textarea>'
									    .'<label class=\"mdl-textfield__label\" for=\"EditFormDetails\">Задайте какие-либо вопросы, <br/>или расскажите о своем вдохновении</label>'
									.'</div>'
								.'</div>'
								.'<div class=\"mdl-grid mdl-card__subtitle-text\">'
									.'<div class=\"mdl-cell mdl-cell--3-col\">Приложите фотографии или эскизы</div>'
									.'<div class=\"mdl-cell mdl-cell--8-col form-group field-orderform-customize has-success\">'
										.str_replace('"', '\"', FileAttachment::widget(['orderId' => $order->id, 'mainForm' => 'OrderForm']))
									.'</div>'
								.'</div>'
							.'</form>'
							.'<div class=\"mdl-card__actions mdl-card--border\">'
								.'<a id=\"action_order\" class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--colored\">'
									.'Сохранить'
							    .'</a>'
								.'<a id=\"edit_order\" class=\"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\" href=\"'.Url::toRoute(['', 'id' => $order->id, '#' => 'history']).'\">'
									.'Отмена'
							    .'</a>'
							.'</div>'
						.'</div>");'
		.'componentHandler.upgradeElements($(".mdl-textfield").get());'
		.'getAllUploads();'
	.'};'
	.'$(window).trigger("hashchange");', View::POS_READY);

function drawCloseCard($order) {
	if ($order->closeDate === null) return;
	return '<div class=\"close-card mdl-card mdl-shadow--2dp\">'
			.'<div class=\"mdl-card__title\">'
    			.'<h2 class=\"mdl-card__title-text\">Заказ закрыт</h2>'
				.'<time class=\"mdl-color-text--grey-600\">'.date('d.m.Y', strtotime($order->closeDate)).'</time>'
  			.'</div>'
			.'<div class=\"mdl-card__supporting-text\">'
			    .'Если вы хотите открыть заказ, сделайте это ниже.'
			.'</div>'
		.'</div>';
}

?>
<div class="order-view mdl-grid">
	<div class="mdl-cell mdl-cell--3-col">
		<nav class="sidebar-nav">
			<ul>
				<li class="is-active">
					<?php echo Html::a('История', ['', 'id' => $order->id, '#' => 'history'])?>
				</li>
				<li class="">
					<?php echo Html::a('Сообщения', ['', 'id' => $order->id, '#' => 'messages'])?>
				</li>
				<li class="">
					<?php echo Html::a('Предложения', ['', 'id' => $order->id, '#' => 'proposals'])?>
				</li>
			</ul>
		</nav>
	</div>
	<div id="tab-content" class="mdl-cell mdl-cell--9-col"></div>
</div>